version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db-mysql-integration
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db-mysql-integration
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    container_name: "adminer"
    image: adminer
    logging:
      driver: none
    restart: always
    ports:
      - 8080:8080