name: Build
on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: docker-compose up
        run: npm run docker:up

      - name: Install dependencies
        run: npm i

      - name: Sleep for 120 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "120s"

      - name: Test and coverage
        run: npm run test:ci
        env:
          DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
