name: Build
on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    env:
      DATABASE_TEST_URL: "mysql://root:123@127.0.0.1:3306/app"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: docker-compose up
        run: npm run docker:up

      - name: sleep 30s
        run: sleep 30s

      - name: check running containers
        run: docker ps

      - name: log database
        run: docker logs db-mysql-integration

      - name: Install dependencies
        run: npm i

      - name: Test and coverage
        run: npm run test:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
